export const foodOptions = [
  // Breakfast
  { name: "Poha", unit: "gm" },
  { name: "Upma", unit: "gm" },
  { name: "Idli", unit: "no." },
  { name: "Dosa", unit: "no." },
  { name: "Masala Dosa", unit: "no." },
  { name: "Plain Dosa", unit: "no." },
  { name: "Medu Vada", unit: "no." },
  { name: "Paratha (Aloo)", unit: "no." },
  { name: "Paratha (Gobi)", unit: "no." },
  { name: "Paratha (Paneer)", unit: "no." },
  { name: "Thepla", unit: "no." },
  { name: "Bread Butter", unit: "no." },
  { name: "Bread Jam", unit: "no." },
  { name: "Omelette", unit: "no." },
  { name: "Boiled Eggs", unit: "no." },
  { name: "Maggi", unit: "gm" },

  // Lunch / Dinner
  { name: "Roti", unit: "no." },
  { name: "Chapati", unit: "no." },
  { name: "Phulka", unit: "no." },
  { name: "Dal Tadka", unit: "gm" },
  { name: "Dal Fry", unit: "gm" },
  { name: "Plain Dal", unit: "gm" },
  { name: "Jeera Rice", unit: "gm" },
  { name: "Steamed Rice", unit: "gm" },
  { name: "Curd Rice", unit: "gm" },
  { name: "Sambar Rice", unit: "gm" },
  { name: "Rajma Chawal", unit: "gm" },
  { name: "Chole Chawal", unit: "gm" },
  { name: "Kadhi Chawal", unit: "gm" },
  { name: "Vegetable Pulao", unit: "gm" },
  { name: "Veg Biryani", unit: "gm" },
  { name: "Chicken Biryani", unit: "gm" },
  { name: "Egg Curry", unit: "gm" },
  { name: "Chicken Curry", unit: "gm" },
  { name: "Fish Curry", unit: "gm" },
  { name: "Paneer Butter Masala", unit: "gm" },
  { name: "Palak Paneer", unit: "gm" },
  { name: "Mix Veg Sabzi", unit: "gm" },
  { name: "Aloo Sabzi", unit: "gm" },
  { name: "Bhindi Fry", unit: "gm" },
  { name: "Baingan Bharta", unit: "gm" },
  { name: "Cabbage Sabzi", unit: "gm" },
  { name: "Lauki Sabzi", unit: "gm" },

  // Maharashtrian
  { name: "Misal Pav", unit: "gm" },
  { name: "Usal Pav", unit: "gm" },
  { name: "Vada Pav", unit: "no." },
  { name: "Sabudana Khichdi", unit: "gm" },
  { name: "Pithla Bhakri", unit: "gm" },
  { name: "Zunka Bhakri", unit: "gm" },
  { name: "Thalipeeth", unit: "no." },
  { name: "Kanda Poha", unit: "gm" },

  // North Indian
  { name: "Chole Bhature", unit: "gm" },
  { name: "Aloo Puri", unit: "gm" },
  { name: "Paneer Paratha", unit: "no." },
  { name: "Dal Makhani", unit: "gm" },
  { name: "Butter Chicken", unit: "gm" },
  { name: "Shahi Paneer", unit: "gm" },

  // South Indian
  { name: "Rasam", unit: "gm" },
  { name: "Lemon Rice", unit: "gm" },
  { name: "Tamarind Rice", unit: "gm" },
  { name: "Appam", unit: "no." },
  { name: "Puttu", unit: "gm" },

  // Street food
  { name: "Pani Puri", unit: "no." },
  { name: "Bhel Puri", unit: "gm" },
  { name: "Sev Puri", unit: "no." },
  { name: "Dahi Puri", unit: "no." },
  { name: "Pav Bhaji", unit: "gm" },
  { name: "Samosa", unit: "no." },
  { name: "Kachori", unit: "no." },
  { name: "Dabeli", unit: "no." },
  { name: "Frankie Roll", unit: "no." },
  { name: "Veg Sandwich", unit: "no." },
  { name: "Grilled Sandwich", unit: "no." },

  // Snacks
  { name: "Pakoda", unit: "gm" },
  { name: "Aloo Bonda", unit: "no." },
  { name: "Murukku", unit: "gm" },
  { name: "Namkeen Mixture", unit: "gm" },
  { name: "Roasted Peanuts", unit: "gm" },

  // Drinks
  { name: "Chai", unit: "ml" },
  { name: "Filter Coffee", unit: "ml" },
  { name: "Lassi", unit: "ml" },
  { name: "Buttermilk", unit: "ml" },
  { name: "Sugarcane Juice", unit: "ml" },

  // Sweets
  { name: "Gulab Jamun", unit: "no." },
  { name: "Rasgulla", unit: "no." },
  { name: "Jalebi", unit: "gm" },
  { name: "Kaju Katli", unit: "gm" },
  { name: "Besan Ladoo", unit: "no." },
  { name: "Rava Kesari", unit: "gm" },
];
